### ISSUE TITLE
1.0.4: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [aio-libs/pytest-aiohttp#50]
Looks like some updates are needed for latest `pytest` 7.2.0

<details>

```console
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.15, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pytest-aiohttp-1.0.4, configfile: setup.cfg, testpaths: tests
plugins: aiohttp-1.0.4, asyncio-0.20.2
asyncio: mode=auto
collected 10 items

tests/test_fixtures.py FFFF                                                                                                                                          [ 40%]
tests/test_obsolete_fixtures.py ...                                                                                                                                  [ 70%]
tests/test_switch_mode.py ...                                                                                                                                        [100%]

================================================================================= FAILURES =================================================================================
___________________________________________________________________________ test_aiohttp_plugin ____________________________________________________________________________
/home/tkloczko/rpmbuild/BUILD/pytest-aiohttp-1.0.4/tests/test_fixtures.py:107: in test_aiohttp_plugin
    result.assert_outcomes(passed=8)
/usr/lib/python3.8/site-packages/_pytest/pytester.py:567: in parseoutcomes
    return self.parse_summary_nouns(self.outlines)
/usr/lib/python3.8/site-packages/_pytest/pytester.py:585: in parse_summary_nouns
    raise ValueError("Pytest terminal summary report not found")
E   ValueError: Pytest terminal summary report not found
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1170, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1135, in inline_run
    ret = main([str(x) for x in args], plugins=plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 148, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.8/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1058, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1346, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1229, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 288, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 489, in register
    ret: Optional[str] = super().register(plugin, name)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 103, in register
    hookimpl_opts = self.parse_hookimpl_opts(plugin, name)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 460, in parse_hookimpl_opts
    return _get_legacy_hook_marks(
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 374, in _get_legacy_hook_marks
    warn_explicit_for(cast(FunctionType, method), message)
  File "/usr/lib/python3.8/site-packages/_pytest/warning_types.py", line 171, in warn_explicit_for
    raise type(w)(f"{w}\n at {filename}:{lineno}") from None
pytest.PytestDeprecationWarning: The hookimpl pytest_configure uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(tryfirst=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
 at /home/tkloczko/rpmbuild/BUILDROOT/python-pytest-aiohttp-1.0.4-5.fc35.x86_64/usr/lib/python3.8/site-packages/pytest_aiohttp/plugin.py:21
_________________________________________________________________________ test_aiohttp_raw_server __________________________________________________________________________
/home/tkloczko/rpmbuild/BUILD/pytest-aiohttp-1.0.4/tests/test_fixtures.py:142: in test_aiohttp_raw_server
    result.assert_outcomes(passed=1)
/usr/lib/python3.8/site-packages/_pytest/pytester.py:567: in parseoutcomes
    return self.parse_summary_nouns(self.outlines)
/usr/lib/python3.8/site-packages/_pytest/pytester.py:585: in parse_summary_nouns
    raise ValueError("Pytest terminal summary report not found")
E   ValueError: Pytest terminal summary report not found
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1170, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1135, in inline_run
    ret = main([str(x) for x in args], plugins=plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 148, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.8/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1058, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1346, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1229, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 288, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 489, in register
    ret: Optional[str] = super().register(plugin, name)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 103, in register
    hookimpl_opts = self.parse_hookimpl_opts(plugin, name)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 460, in parse_hookimpl_opts
    return _get_legacy_hook_marks(
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 374, in _get_legacy_hook_marks
    warn_explicit_for(cast(FunctionType, method), message)
  File "/usr/lib/python3.8/site-packages/_pytest/warning_types.py", line 171, in warn_explicit_for
    raise type(w)(f"{w}\n at {filename}:{lineno}") from None
pytest.PytestDeprecationWarning: The hookimpl pytest_configure uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(tryfirst=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
 at /home/tkloczko/rpmbuild/BUILDROOT/python-pytest-aiohttp-1.0.4-5.fc35.x86_64/usr/lib/python3.8/site-packages/pytest_aiohttp/plugin.py:21
____________________________________________________________ test_aiohttp_client_cls_fixture_custom_client_used ____________________________________________________________
/home/tkloczko/rpmbuild/BUILD/pytest-aiohttp-1.0.4/tests/test_fixtures.py:169: in test_aiohttp_client_cls_fixture_custom_client_used
    result.assert_outcomes(passed=1)
/usr/lib/python3.8/site-packages/_pytest/pytester.py:567: in parseoutcomes
    return self.parse_summary_nouns(self.outlines)
/usr/lib/python3.8/site-packages/_pytest/pytester.py:585: in parse_summary_nouns
    raise ValueError("Pytest terminal summary report not found")
E   ValueError: Pytest terminal summary report not found
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1170, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1135, in inline_run
    ret = main([str(x) for x in args], plugins=plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 148, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.8/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1058, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1346, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1229, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 288, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 489, in register
    ret: Optional[str] = super().register(plugin, name)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 103, in register
    hookimpl_opts = self.parse_hookimpl_opts(plugin, name)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 460, in parse_hookimpl_opts
    return _get_legacy_hook_marks(
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 374, in _get_legacy_hook_marks
    warn_explicit_for(cast(FunctionType, method), message)
  File "/usr/lib/python3.8/site-packages/_pytest/warning_types.py", line 171, in warn_explicit_for
    raise type(w)(f"{w}\n at {filename}:{lineno}") from None
pytest.PytestDeprecationWarning: The hookimpl pytest_configure uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(tryfirst=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
 at /home/tkloczko/rpmbuild/BUILDROOT/python-pytest-aiohttp-1.0.4-5.fc35.x86_64/usr/lib/python3.8/site-packages/pytest_aiohttp/plugin.py:21
_________________________________________________________________ test_aiohttp_client_cls_fixture_factory __________________________________________________________________
/home/tkloczko/rpmbuild/BUILD/pytest-aiohttp-1.0.4/tests/test_fixtures.py:220: in test_aiohttp_client_cls_fixture_factory
    result.assert_outcomes(passed=2)
/usr/lib/python3.8/site-packages/_pytest/pytester.py:567: in parseoutcomes
    return self.parse_summary_nouns(self.outlines)
/usr/lib/python3.8/site-packages/_pytest/pytester.py:585: in parse_summary_nouns
    raise ValueError("Pytest terminal summary report not found")
E   ValueError: Pytest terminal summary report not found
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1170, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1135, in inline_run
    ret = main([str(x) for x in args], plugins=plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 148, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.8/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1058, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1346, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1229, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 288, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 489, in register
    ret: Optional[str] = super().register(plugin, name)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 103, in register
    hookimpl_opts = self.parse_hookimpl_opts(plugin, name)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 460, in parse_hookimpl_opts
    return _get_legacy_hook_marks(
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 374, in _get_legacy_hook_marks
    warn_explicit_for(cast(FunctionType, method), message)
  File "/usr/lib/python3.8/site-packages/_pytest/warning_types.py", line 171, in warn_explicit_for
    raise type(w)(f"{w}\n at {filename}:{lineno}") from None
pytest.PytestDeprecationWarning: The hookimpl pytest_configure uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(tryfirst=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
 at /home/tkloczko/rpmbuild/BUILDROOT/python-pytest-aiohttp-1.0.4-5.fc35.x86_64/usr/lib/python3.8/site-packages/pytest_aiohttp/plugin.py:21
========================================================================= short test summary info ==========================================================================
FAILED tests/test_fixtures.py::test_aiohttp_plugin - ValueError: Pytest terminal summary report not found
FAILED tests/test_fixtures.py::test_aiohttp_raw_server - ValueError: Pytest terminal summary report not found
FAILED tests/test_fixtures.py::test_aiohttp_client_cls_fixture_custom_client_used - ValueError: Pytest terminal summary report not found
FAILED tests/test_fixtures.py::test_aiohttp_client_cls_fixture_factory - ValueError: Pytest terminal summary report not found
======================================================================= 4 failed, 6 passed in 3.02s ========================================================================
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-8fb365bf-55c2-45dd-bf96-208f54d343b4
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-tkloczko/garbage-8fb365bf-55c2-45dd-bf96-208f54d343b4'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-439f487e-9bb6-422e-8b73-84b1c517a616/test_rmtree_errorhandler_rerai0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_rmtree_errorhandler_rerai0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-439f487e-9bb6-422e-8b73-84b1c517a616/test_rmtree_errorhandler_reado0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_rmtree_errorhandler_reado0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-439f487e-9bb6-422e-8b73-84b1c517a616/test_safe_delete_no_perms0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_safe_delete_no_perms0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-439f487e-9bb6-422e-8b73-84b1c517a616/test_safe_set_no_perms0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_safe_set_no_perms0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-439f487e-9bb6-422e-8b73-84b1c517a616/test_safe_get_no_perms0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_safe_get_no_perms0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-439f487e-9bb6-422e-8b73-84b1c517a616
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-tkloczko/garbage-439f487e-9bb6-422e-8b73-84b1c517a616'
  warnings.warn(
```
</details>

**Comment by kloczek** [comment]
Just tested 1.0.5 and all looks good now.
Thank you 👍 😄 
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-aiohttp-1.0.5-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-aiohttp-1.0.5-2.fc
35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network'
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-7.4.1, pluggy-1.3.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pytest-aiohttp-1.0.5
configfile: setup.cfg
testpaths: tests
plugins: aiohttp-1.0.5, asyncio-0.21.1
asyncio: mode=auto
collected 10 items

tests/test_fixtures.py ....                                              [ 40%]
tests/test_obsolete_fixtures.py ...                                      [ 70%]
tests/test_switch_mode.py ...                                            [100%]

============================== 10 passed in 2.91s ==============================
```
